repos:
  # Rust formatting
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        name: cargo fmt
        description: Format Rust code with rustfmt
      - id: cargo-check
        name: cargo check
        description: Check Rust code compiles
      - id: clippy
        name: cargo clippy
        description: Lint Rust code with clippy
        args: ['--all-targets', '--all-features', '--', '-D', 'warnings']

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
